#!/usr/bin/perl

use strict;
use Getopt::Long;
use Encode;
use IO::File;

sub usage { print "Usage: $0 [-h] [-c|--convert input output]\n" }


my ( $o, @c, $h);
my $BOM = chr(hex "0xEF"). chr(hex "0xBB"). chr(hex "0xBF");

GetOptions(
    "o|option=s" => \$o,
    "convert=s{2}" => \@c, # no need for c|convert
#    "help" => \$help,
    "h|help"     => \$h,
    )
or die usage;


usage() if $h;

if (@c) {
    my $input_file = $c[0];
    my $output_file = $c[1];
    my $input_fh = IO::File->new($input_file, '<') or die "$input_file: $!";
    my $output_fh = IO::File->new($output_file, '+>:raw') or die "$output_file: $!";

    print $output_fh "$BOM";

    while (my $line = <$input_fh>) {
        my $octets = decode("iso-8859-7", $line);
        my $uline = encode("utf-8", $octets);
        print $output_fh $uline;
    }

    $input_fh->close();
    $output_fh->close();
}

#print "$0: c args=@c: @ARGV\n";   
#print "$0: c args:@c \n";
#print "$0: $c[1]\n";

