.TH SUBFIX 1 subfix\-VERSION
.SH NAME
subfix \- Fix subtitle encoding
.SH SYNOPSIS
.B subfix [ -h ][ -c iso88597.srt utf8.srt ][ -s iso88597.srt utf8.srt ]
.SH DESCRIPTION
subfix is a perl script that changes the encoding of subtitle files.
Some televisions do not support iso8859 subtitles and this is when
subfix is useful. Currently, subfix only converts greek subs (iso8859-7) to utf8.
.br

.SH OPTIONS
.TP
.B \-h, \-\-help
Show the help message and exit.
.TP
.B \-c, \-\-convert
Convert input subtitle to utf8, without stripping text formatting (bold, italics, etc)
.TP
.B \-s, \-\-strip
Like \-c, but also strip text formatting.

.SH "EXAMPLES"
1. Convert iso88597.srt subtitle to utf8.srt without stripping text formatting:

subfix -c iso88597.srt utf8.srt

2. Convert iso88597.srt subtitle to utf8.srt and strip text formatting: 

subfix -s iso88597.srt utf8.srt

.SH BUGS
Please report any bugs or share any suggestions by hitting me a /msg on irc:
dwts@freenode or join #ninja-turtles @freenode.
.SH REPO
The latest version of peek can be found here:

https://github.com/s-p-k/subfix

.SH COPYRIGHT
Copyright (c) 2014-2015, Pavlos Moysidis (mr.dwts@gmail.com)
